window.levelUpProducts = [
  ["warcraft", "Warcraft", "Игровые товары", "catalog", "PC", "Blizzard", "KG · скоро РФ", 100, "Игровые товары для мира Warcraft: начните подбор и сохраните заявку в личном кабинете."],
  ["world-of-warcraft", "World of Warcraft", "Золото и подписка", "catalog", "PC", "Blizzard", "KG · скоро РФ", 250, "Подбор золота и подписки для World of Warcraft. Финальные параметры подтверждает поддержка."],
  ["counter-strike", "Counter-Strike", "Скины и баланс", "catalog", "PC", "Valve", "KG · скоро РФ", 150, "Подбор игровых товаров и баланса для Counter-Strike."],
  ["cs2", "CS2", "Предметы и баланс", "catalog", "PC", "Valve", "KG · скоро РФ", 150, "Предметы и баланс для CS2. Доступность подтверждается до оформления.", "Хит продаж"],
  ["mobile-legends", "Mobile Legends", "Алмазы", "currency", "Mobile", "Moonton", "KG · скоро РФ", 80, "Игровая валюта и наборы для Mobile Legends.", "Хит продаж"],
  ["pubg", "PUBG", "UC и предметы", "currency", "PC", "KRAFTON", "KG · скоро РФ", 120, "UC и игровые предметы для PUBG." , "Хит продаж"],
  ["quake", "Quake", "Игровой баланс", "catalog", "PC", "Bethesda", "KG · скоро РФ", 100, "Подбор игрового баланса и товаров для Quake."],
  ["street-fighter", "Street Fighter", "Игровые товары", "catalog", "PC", "Capcom", "KG · скоро РФ", 150, "Игровые товары для Street Fighter — подбор через заявку."],
  ["apex-legends", "Apex Legends", "Монеты и наборы", "currency", "PC", "EA", "EA · KG", 120, "Монеты и наборы для Apex Legends."],
  ["ea-sports-fc", "EA SPORTS FC", "Points и Ultimate Team", "currency", "PC", "EA", "EA · KG", 150, "Points и наборы Ultimate Team для EA SPORTS FC.", "Хит продаж"],
  ["battlefield", "Battlefield", "Баланс и наборы", "currency", "PC", "EA", "EA · KG", 180, "Баланс и наборы для Battlefield."],
  ["the-sims-4", "The Sims 4", "Дополнения", "dlc", "PC", "EA", "EA · KG", 200, "Дополнения и контент для The Sims 4."],
  ["need-for-speed", "Need for Speed", "Контент и баланс", "currency", "PC", "EA", "EA · KG", 130, "Контент и игровой баланс для Need for Speed."],
  ["ea-sports-f1", "EA SPORTS F1", "Контент сезона", "dlc", "PC", "EA", "EA · KG", 190, "Сезонный контент для EA SPORTS F1."],
  ["plants-vs-zombies-2", "Plants vs. Zombies 2", "Самоцветы и растения", "currency", "Mobile", "EA", "EA · KG", 70, "Самоцветы и растения для Plants vs. Zombies 2."],
  ["star-wars-goh", "Star Wars: Galaxy of Heroes", "Кристаллы", "currency", "Mobile", "EA", "EA · KG", 100, "Кристаллы для Star Wars: Galaxy of Heroes."],
  ["real-racing-3", "Real Racing 3", "Золото и валюта", "currency", "Mobile", "EA", "EA · KG", 70, "Золото и игровая валюта для Real Racing 3."],
  ["madden-nfl-mobile", "Madden NFL Mobile", "Points и паки", "currency", "Mobile", "EA", "EA · KG", 100, "Points и паки для Madden NFL Mobile."],
  ["tekken-8", "TEKKEN 8", "Контент и персонажи", "dlc", "PC", "Bandai Namco", "Bandai · KG", 220, "Контент и персонажи для TEKKEN 8."],
  ["elden-ring", "ELDEN RING", "Дополнения", "dlc", "PC", "Bandai Namco", "Bandai · KG", 250, "Дополнения для ELDEN RING."],
  ["dragon-ball-sparking-zero", "DRAGON BALL: Sparking! ZERO", "Персонажи и DLC", "dlc", "PC", "Bandai Namco", "Bandai · KG", 200, "Персонажи и DLC для DRAGON BALL: Sparking! ZERO."],
  ["dragon-ball-xenoverse-2", "DRAGON BALL XENOVERSE 2", "TP Medals и DLC", "dlc", "PC", "Bandai Namco", "Bandai · KG", 150, "TP Medals и DLC для DRAGON BALL XENOVERSE 2."],
  ["digimon-story", "Digimon Story", "Дополнения", "dlc", "PC", "Bandai Namco", "Bandai · KG", 180, "Дополнения для Digimon Story.", "Новинка"],
  ["little-nightmares-iii", "Little Nightmares III", "Игровой контент", "catalog", "PC", "Bandai Namco", "Bandai · KG", 170, "Игровой контент для Little Nightmares III.", "Новинка"],
  ["code-vein-ii", "CODE VEIN II", "Контент и DLC", "dlc", "PC", "Bandai Namco", "Bandai · KG", 210, "Контент и DLC для CODE VEIN II.", "Новинка"],
  ["tales-of-arise", "Tales of Arise", "Дополнения", "dlc", "PC", "Bandai Namco", "Bandai · KG", 180, "Дополнения для Tales of Arise."],
  ["ace-combat-7", "ACE COMBAT 7", "Самолёты и DLC", "dlc", "PC", "Bandai Namco", "Bandai · KG", 160, "Самолёты и DLC для ACE COMBAT 7."],
  ["naruto-to-boruto", "NARUTO TO BORUTO", "Shinobi Striker", "catalog", "PC", "Bandai Namco", "Bandai · KG", 130, "Игровой контент для NARUTO TO BORUTO."],
  ["one-piece-pirate-warriors-4", "ONE PIECE Pirate Warriors 4", "Персонажи и DLC", "dlc", "PC", "Bandai Namco", "Bandai · KG", 190, "Персонажи и DLC для ONE PIECE Pirate Warriors 4."],
  ["pac-man", "PAC-MAN", "Аркадный контент", "catalog", "PC", "Bandai Namco", "Bandai · KG", 90, "Аркадный контент для PAC-MAN."]
].map(([id, title, offer, category, platform, publisher, region, price, description, badge]) => ({ id, title, offer, category, platform, publisher, region, price, description, badge: badge || "" }));
